


source 'https://github.com/CocoaPods/Specs.git'


target "dotEngine-ios-exmaple" do
    pod 'AFNetworking'
    pod 'Toast'
    pod 'GPUImage'
    pod 'DotGPUBeautyFilter', :git => 'https://github.com/dotEngine/DotGPUBeautyFilter.git'
    pod 'libdotEngine', :git => 'https://github.com/dotEngine/dotEngine-ios-sdk.git'
end
